
name: Update JSON

on:
  push:
    branches: [ "test-ghaction" ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Download csv
      run: |
        python download-csv.py gid.json csv
    - name: Convert to json
      run: |
        python csv-to-json.py csv json

